In [1]:
from utils import create_facts_and_examples
import numpy as np
import pandas as pd
import random, os
np.random.seed(0) #Code B


In [2]:
N = 30
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)

customer = ['c'+str(i+16000) for i in range(90)]
merchant = ['m'+str(j+32000) for j in range(10)]

Target = A & B & C# & D
df = pd.DataFrame({'orig':np.random.choice(customer+merchant, size=N), 'destination':np.random.choice(merchant, size=N), 'A':A, 'B':B, "C":C, "D":D, "Target":Target})


In [3]:
fromM2M = df[df['orig'].map(lambda x:x[0])=='m'].reset_index()

In [4]:
fraudsters = df[df['Target']==True]

### finding an index where trasnactions from Merchant to merchant were performed by a fraudster and assign those transactions a flag true

In [5]:
index_sr = pd.merge(fromM2M.reset_index(), fraudsters[['destination']].drop_duplicates(), how='inner', left_on='orig', right_on='destination')['index']

In [6]:
df['Cons_orig']=0
df.loc[index_sr,'Target']=1
df.loc[index_sr,'Cons_orig']=1
df['From_orig']=1
df['To_destination']=1

In [7]:
df.loc[index_sr,:]

orig destination  A  B  C  D  Target  Cons_orig  From_orig  \
18  m32003      m32000  0  0  1  1       1          1          1   
20  m32008      m32000  0  0  0  1       1          1          1   

    To_destination  
18               1  
20               1

In [8]:
df

orig destination  A  B  C  D  Target  Cons_orig  From_orig  \
0   c16023      m32002  0  1  1  1       0          0          1   
1   c16079      m32009  1  0  0  1       0          0          1   
2   c16013      m32002  1  1  1  0       1          0          1   
3   c16085      m32003  0  0  0  0       0          0          1   
4   c16048      m32003  1  1  1  1       1          0          1   
5   c16049      m32002  1  1  0  0       0          0          1   
6   c16069      m32003  1  0  0  0       0          0          1   
7   c16041      m32004  1  1  0  1       0          0          1   
8   c16035      m32001  1  1  0  1       0          0          1   
9   c16064      m32002  1  0  0  0       0          0          1   
10  m32005      m32009  1  0  1  1       0          0          1   
11  c16069      m32001  0  1  1  0       0          0          1   
12  m32004      m32004  0  0  0  0       0          0          1   
13  c16000      m32006  1  1  0  1       0          0          1   
14  c16050      m32008  0  1  0  0       0          0          1   
15  c16036      m32002  0  1  1  0       0          0          1   
16  c16034      m32003  0  1  1  0       0          0          1   
17  c16048      m32000  0  1  0  1       0          0          1   
18  m32003      m32000  0  0  1  1       1          1          1   
19  c16003      m32006  1  1  0  0       0          0          1   
20  m32008      m32000  0  0  0  1       1          1          1   
21  c16042      m32006  1  1  1  0       1          0          1   
22  c16077      m32003  1  1  0  0       0          0          1   
23  c16021      m32003  0  1  1  0       0          0          1   
24  c16073      m32008  0  1  1  0       0          0          1   
25  c16000      m32008  1  0  1  0       0          0          1   
26  c16010      m32008  1  1  1  1       1          0          1   
27  c16043      m32002  1  0  1  0       0          0          1   
28  c16058      m32003  1  0  1  1       0          0          1   
29  c16023      m32002  0  1  0  0       0          0          1   

    To_destination  
0                1  
1                1  
2                1  
3                1  
4                1  
5                1  
6                1  
7                1  
8                1  
9                1  
10               1  
11               1  
12               1  
13               1  
14               1  
15               1  
16               1  
17               1  
18               1  
19               1  
20               1  
21               1  
22               1  
23               1  
24               1  
25               1  
26               1  
27               1  
28               1  
29               1

In [9]:
df[df['orig'].str[0]=='m']

orig destination  A  B  C  D  Target  Cons_orig  From_orig  \
10  m32005      m32009  1  0  1  1       0          0          1   
12  m32004      m32004  0  0  0  0       0          0          1   
18  m32003      m32000  0  0  1  1       1          1          1   
20  m32008      m32000  0  0  0  1       1          1          1   

    To_destination  
10               1  
12               1  
18               1  
20               1

In [10]:
df['orig'] = df['orig'].str[1:].astype('int')
df['destination'] = df['destination'].str[1:].astype('int')

In [11]:
create_facts_and_examples(df_= df, target='Target', 
                          predicates=['A', 'B', 'C', 'Cons_orig', 'From_orig', 'To_destination'], output_dir="examples/chain-fraud")

Target
[ 2  4 18 20 21 26]
A
[ 1  2  4  5  6  7  8  9 10 13 19 21 22 25 26 27 28]
B
[ 0  2  4  5  7  8 11 13 14 15 16 17 19 21 22 23 24 26 29]
C
[ 0  2  4 10 11 15 16 18 21 23 24 25 26 27 28]
Cons_orig
Cons_orig 18 32003
Cons_orig 20 32008
From_orig
From_orig 0 16023
From_orig 1 16079
From_orig 2 16013
From_orig 3 16085
From_orig 4 16048
From_orig 5 16049
From_orig 6 16069
From_orig 7 16041
From_orig 8 16035
From_orig 9 16064
From_orig 10 32005
From_orig 11 16069
From_orig 12 32004
From_orig 13 16000
From_orig 14 16050
From_orig 15 16036
From_orig 16 16034
From_orig 17 16048
From_orig 18 32003
From_orig 19 16003
From_orig 20 32008
From_orig 21 16042
From_orig 22 16077
From_orig 23 16021
From_orig 24 16073
From_orig 25 16000
From_orig 26 16010
From_orig 27 16043
From_orig 28 16058
From_orig 29 16023
To_destination
To_destination 0 32002
To_destination 1 32009
To_destination 2 32002
To_destination 3 32003
To_destination 4 32003
To_destination 5 32002
To_destination 6 32003
To_destination