In [1]:
from utils import create_facts_and_examples
import numpy as np
import pandas as pd


In [2]:
N = 100

In [3]:
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)


In [4]:
#create artificial knowledge if A and B then Target

Target = A & B
df = pd.DataFrame({'A':A, 'B':B, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', ], output_dir='examples/a-b')


Target
[ 1 18 23 24 27 28 33 41 44 45 49 61 62 64 70 79 85 86 97 99]
A
[ 0  1  2  8  9 18 21 22 23 24 26 27 28 29 32 33 35 37 40 41 43 44 45 46
 49 52 55 60 61 62 63 64 66 68 70 74 76 79 83 84 85 86 92 94 96 97 98 99]
B
[ 1  4  6  7 10 11 13 14 17 18 19 20 23 24 25 27 28 30 33 36 41 42 44 45
 47 48 49 50 51 53 54 61 62 64 69 70 73 78 79 81 85 86 87 89 90 95 97 99]


In [7]:
#create artificial knowledge if A and B and C then Target
Target = A & B & C
df = pd.DataFrame({'A':A, 'B':B, "C":C, "Target":Target})

create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C"], output_dir='examples/a-b-c')


Target
[ 1 27 33 85 97 99]
A
[ 0  1  2  8  9 18 21 22 23 24 26 27 28 29 32 33 35 37 40 41 43 44 45 46
 49 52 55 60 61 62 63 64 66 68 70 74 76 79 83 84 85 86 92 94 96 97 98 99]
B
[ 1  4  6  7 10 11 13 14 17 18 19 20 23 24 25 27 28 30 33 36 41 42 44 45
 47 48 49 50 51 53 54 61 62 64 69 70 73 78 79 81 85 86 87 89 90 95 97 99]
C
[ 0  1  2  3  4  5  7  9 13 19 21 22 25 27 32 33 35 36 37 38 39 40 42 43
 50 51 56 57 59 67 68 71 72 74 80 81 82 85 88 94 96 97 99]


In [8]:
N = 100
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)

Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d')


Target
[10 28 35 76 90]
A
[ 3  6  9 10 12 13 15 16 17 18 21 23 24 26 28 30 32 33 35 36 38 40 41 44
 45 46 49 54 56 57 58 60 61 63 64 65 66 67 70 71 73 74 75 76 78 80 83 87
 89 90 94]
B
[ 1  3  7  8 10 11 12 13 14 15 16 18 19 21 25 28 31 34 35 36 38 39 40 43
 51 53 55 59 60 61 62 63 64 65 67 70 71 72 73 74 76 80 84 85 86 88 89 90
 92 93 96 97 98]
C
[ 1  6  8  9 10 13 15 17 19 20 21 22 23 24 28 31 32 35 39 42 43 44 47 49
 50 51 52 56 57 62 63 65 67 70 72 73 75 76 81 82 83 84 87 90 94 96 99]
D
[ 0  2  3  5  7  8  9 10 11 12 17 20 24 25 27 28 29 33 35 37 38 42 44 45
 48 49 51 53 54 55 57 58 59 61 66 69 72 75 76 77 78 81 83 84 86 87 88 90
 91 92 93 94 96 98 99]


In [9]:
N = 100
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)
A[0:20]=1
B[0:20]=1
C[0:20]=1
D[0:20]=1
Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d-first-20-true')


Target
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 22 35 62 67
 84]
A
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 26
 27 30 32 33 34 35 36 37 39 40 45 46 51 56 57 60 61 62 63 67 69 70 76 77
 79 84 85 87 90 91 92 93 94 95]
B
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 21 22 23 24
 25 28 30 34 35 37 39 40 44 45 46 47 49 55 59 61 62 63 64 66 67 69 71 72
 74 75 77 78 80 84 87 88 91 93 96 98]
C
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 27
 28 29 30 31 33 34 35 42 44 48 49 50 53 56 57 62 64 65 66 67 68 70 73 74
 75 76 77 80 82 83 84 85 86 88 89 95 98 99]
D
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 22 23 25
 28 29 32 35 38 40 42 43 47 49 53 54 56 57 58 60 61 62 64 65 67 70 71 73
 75 76 78 80 81 84 85 86 87 88 89 90 91 92 94 96 97 99]


In [10]:
N = 1000
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)

Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d-1000')


Target
[  2  10  43  69  72  90 103 104 106 142 145 160 164 188 209 210 215 226
 236 244 246 255 266 270 280 283 291 305 310 324 361 364 368 380 418 423
 451 456 468 483 512 534 536 595 635 637 658 674 689 691 712 740 748 765
 774 794 806 808 830 839 848 854 866 890 912 931 950 966 977 982 989]
A
[  0   2   3   4   5   7   9  10  11  13  14  17  18  20  25  27  30  33
  37  40  41  43  44  46  47  50  52  54  55  56  60  61  62  63  65  66
  69  72  79  81  84  86  90  91  92  93  95  96  97  98  99 100 102 103
 104 105 106 108 109 110 111 113 116 118 119 120 121 122 125 126 127 128
 129 130 133 137 139 141 142 143 145 146 147 149 151 154 158 159 160 161
 162 164 166 167 169 170 171 173 174 175 177 178 179 180 181 184 185 186
 188 192 194 196 197 198 199 200 202 207 208 209 210 211 213 215 216 217
 218 219 220 225 226 229 230 233 234 236 238 241 242 244 245 246 249 250
 251 252 253 254 255 256 259 261 262 263 266 267 268 269 270 271 274 278
 280 283 287 288 290 291 297 298 300 301 302 