In [1]:
from utils import create_facts_and_examples
import numpy as np
import pandas as pd


In [2]:
N = 100

In [3]:
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)


In [4]:
#create artificial knowledge if A and B then Target

Target = A & B
df = pd.DataFrame({'A':A, 'B':B, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', ], output_dir='examples/a-b')


Target
[25 26 29 31 40 42 44 53 62 65 70 73 77 80 81 82 86 88 90 91 98]
A
[ 1  3  6 12 15 18 25 26 28 29 31 32 36 40 42 43 44 48 50 53 57 58 59 62
 65 67 68 69 70 72 73 74 77 80 81 82 86 87 88 90 91 94 97 98 99]
B
[ 2  4  5  7  8 13 14 16 17 20 21 25 26 29 30 31 33 34 37 39 40 41 42 44
 46 47 51 52 53 54 60 61 62 65 70 73 77 80 81 82 83 86 88 89 90 91 92 98]


In [5]:
#create artificial knowledge if A and B and C then Target
Target = A & B & C
df = pd.DataFrame({'A':A, 'B':B, "C":C, "Target":Target})
df.to_parquet(path='examples/a-b-c' + '/df.parquet')

create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C"], output_dir='examples/a-b-c')


Target
[25 26 31 40 44 70 77 80 81 82 86 88 98]
A
[ 1  3  6 12 15 18 25 26 28 29 31 32 36 40 42 43 44 48 50 53 57 58 59 62
 65 67 68 69 70 72 73 74 77 80 81 82 86 87 88 90 91 94 97 98 99]
B
[ 2  4  5  7  8 13 14 16 17 20 21 25 26 29 30 31 33 34 37 39 40 41 42 44
 46 47 51 52 53 54 60 61 62 65 70 73 77 80 81 82 83 86 88 89 90 91 92 98]
C
[ 0  1  2  3  4  6 11 14 15 17 21 23 24 25 26 27 30 31 33 34 37 38 39 40
 41 43 44 47 48 50 52 57 58 60 61 63 68 69 70 71 74 75 76 77 78 79 80 81
 82 83 84 85 86 88 92 95 98]


In [6]:
N = 100
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)

Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d')


Target
[10 20 27 37 38 39 62 64 79 84 98]
A
[ 1  5  6  9 10 11 12 17 20 21 24 25 26 27 29 30 31 32 34 37 38 39 43 45
 47 48 49 50 52 53 54 56 59 62 64 66 69 70 71 76 77 78 79 80 82 84 85 88
 89 90 94 95 97 98 99]
B
[ 0  1  6  7 10 12 15 18 19 20 22 24 26 27 28 30 32 35 36 37 38 39 41 42
 44 47 48 51 54 57 58 60 61 62 64 65 66 67 71 74 75 76 78 79 80 81 83 84
 85 88 92 97 98 99]
C
[ 1  3  5  9 10 11 15 17 18 19 20 21 22 23 27 29 32 33 34 36 37 38 39 40
 41 44 45 50 52 57 61 62 63 64 65 67 74 75 77 79 81 84 86 87 89 90 93 95
 97 98 99]
D
[ 0  3  4  6  9 10 13 16 17 18 20 21 22 26 27 29 33 34 36 37 38 39 40 41
 42 46 47 49 51 52 53 54 55 56 58 62 63 64 66 68 69 70 71 72 74 76 78 79
 82 84 85 86 90 92 93 94 96 98]


In [7]:
N = 100
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)
A[0:20]=1
B[0:20]=1
C[0:20]=1
D[0:20]=1
Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d-first-20-true')


Target
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 68 95]
A
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 21 22 24 25
 27 31 34 36 37 39 41 42 44 45 46 47 48 50 52 54 55 56 57 58 60 61 63 66
 68 69 71 72 74 75 80 83 85 87 88 89 90 92 94 95 98]
B
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 23 24
 26 33 36 37 38 39 49 51 52 55 57 60 62 65 66 68 69 70 71 74 75 76 78 80
 81 83 85 87 90 92 95 96 98]
C
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 22 23 27
 28 29 31 32 33 34 35 36 39 45 46 48 49 50 53 55 56 57 62 63 68 71 74 76
 77 78 79 82 84 86 93 94 95 96 97 99]
D
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 23 24 25
 26 27 29 31 32 33 34 37 38 41 42 43 51 52 53 56 58 59 60 61 62 64 65 67
 68 72 76 80 81 82 86 88 89 92 93 95 98 99]


In [8]:
N = 1000
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)

Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d-1000')


Target
[ 32  38  57  93 103 104 109 148 178 195 249 291 321 329 332 333 369 373
 375 383 385 389 407 441 476 481 498 513 547 552 553 609 614 628 640 644
 646 661 698 725 749 766 768 786 792 793 796 817 824 831 835 843 884 907
 910 911 934 941 998]
A
[  4   5   7   9  12  14  15  16  22  25  29  31  32  33  35  36  38  40
  42  45  46  49  50  52  54  57  62  64  66  72  74  75  76  77  79  80
  81  83  84  89  90  93  99 100 101 102 103 104 106 107 109 110 112 115
 117 121 122 123 124 125 127 128 129 130 131 135 137 141 144 148 150 151
 154 155 156 157 161 165 166 169 173 174 178 182 183 184 186 188 189 193
 195 200 202 203 204 207 209 210 211 212 213 214 215 219 221 226 227 228
 229 233 234 235 237 241 242 244 245 247 248 249 251 252 257 258 259 262
 271 272 273 274 275 276 277 279 280 283 287 288 289 291 297 299 303 304
 306 307 310 311 312 314 315 316 318 320 321 323 325 326 328 329 331 332
 333 334 336 337 338 340 347 352 354 355 356 358 359 360 368 369 370 371
 373 375 376 378 380