In [1]:
from utils import create_facts_and_examples
import numpy as np
import pandas as pd


In [2]:
N = 100
np.random.seed(100)

In [3]:
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)


In [4]:
#create artificial knowledge if A and B then Target

Target = A & B
df = pd.DataFrame({'A':A, 'B':B, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', ], output_dir='examples/a-b')


Target
[ 2  4 25 27 34 36 37 42 43 44 45 49 57 60 64 67 68 69 78 80 90 98]
A
[ 2  3  4  5 11 16 19 21 25 26 27 30 33 34 35 36 37 40 41 42 43 44 45 46
 47 49 50 51 54 55 57 59 60 61 64 67 68 69 76 78 80 83 84 88 89 90 91 94
 95 98]
B
[ 0  2  4  6  8  9 12 14 15 22 24 25 27 34 36 37 42 43 44 45 48 49 52 57
 58 60 62 64 66 67 68 69 70 71 72 73 78 80 82 86 90 92 93 96 97 98]


In [5]:
#create artificial knowledge if A and B and C then Target
Target = A & B & C
df = pd.DataFrame({'A':A, 'B':B, "C":C, "Target":Target})

create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C"], output_dir='examples/a-b-c')


Target
[34 36 42 44 49 60 67 68]
A
[ 2  3  4  5 11 16 19 21 25 26 27 30 33 34 35 36 37 40 41 42 43 44 45 46
 47 49 50 51 54 55 57 59 60 61 64 67 68 69 76 78 80 83 84 88 89 90 91 94
 95 98]
B
[ 0  2  4  6  8  9 12 14 15 22 24 25 27 34 36 37 42 43 44 45 48 49 52 57
 58 60 62 64 66 67 68 69 70 71 72 73 78 80 82 86 90 92 93 96 97 98]
C
[ 0  6  7 10 14 16 18 19 23 28 31 32 34 35 36 39 42 44 46 49 51 52 53 54
 56 59 60 65 66 67 68 71 73 74 75 77 79 81 83 84 88 91 94 95 96 99]


In [6]:
N = 100
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)

Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d')


Target
[ 8 13 19 50 87 90 97]
A
[ 0  3  6  8  9 10 11 13 15 16 17 19 20 22 25 26 27 30 33 34 35 36 37 40
 42 48 49 50 55 58 60 61 63 66 68 69 73 74 76 77 79 81 84 85 87 89 90 92
 96 97 98 99]
B
[ 1  3  7  8  9 10 11 13 17 19 21 22 23 24 25 27 29 31 32 37 38 42 44 45
 46 50 53 55 56 57 59 60 66 68 70 73 74 75 76 77 79 80 83 84 85 87 88 90
 94 95 96 97 99]
C
[ 0  2  5  7  8  9 11 12 13 15 16 19 21 22 27 29 30 31 32 35 40 41 44 47
 49 50 51 54 56 58 60 62 63 69 70 72 79 80 81 82 86 87 88 89 90 94 97 99]
D
[ 2  3  4  5  7  8 10 12 13 14 18 19 21 23 24 25 26 28 32 33 36 37 38 40
 41 44 45 49 50 51 54 55 58 59 62 64 68 69 70 71 72 73 83 84 85 86 87 88
 90 93 95 97 98]


In [7]:
N = 100
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)
A[0:20]=1
B[0:20]=1
C[0:20]=1
D[0:20]=1
Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d-first-20-true')


Target
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 22 27 32 72
 76]
A
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 22 24 25 26
 27 28 29 30 32 33 34 36 37 38 39 41 43 45 46 47 48 49 56 58 60 61 63 64
 65 66 67 70 71 72 74 76 77 82 83 84 87 93 94 96 99]
B
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 22 26 27 29
 31 32 33 34 36 38 41 42 44 46 47 50 53 58 60 62 63 65 68 69 70 72 75 76
 78 79 80 84 86 89 90 91 92 93 95 96 98]
C
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 22 23 24 27
 31 32 34 35 36 37 41 45 46 47 48 49 50 51 52 53 55 60 61 62 63 64 65 66
 70 71 72 73 74 76 77 83 85 87 88 91 94 98]
D
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 29 30 31 32 35 37 38 39 40 50 51 54 58 59 61 68 69 71 72 76
 78 80 81 82 83 84 87 91 92 94 96 98 99]


In [8]:
N = 1000
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)

Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d-1000')


Target
[  5  10  59  67  96 100 124 129 137 153 168 207 237 261 280 333 382 396
 404 434 439 455 462 464 499 560 568 571 597 601 617 633 669 698 710 719
 776 804 808 811 819 827 846 855 884 910 969 973 978]
A
[  2   4   5   7   9  10  11  14  23  24  28  32  35  38  39  42  43  45
  46  47  50  51  53  55  59  60  62  63  64  66  67  68  72  73  77  78
  79  80  82  83  84  87  90  96  97  98  99 100 101 102 107 108 109 112
 113 114 116 118 121 123 124 126 127 129 131 134 135 136 137 138 140 143
 144 145 147 148 149 150 152 153 155 157 167 168 169 170 174 175 177 178
 179 185 190 193 196 197 199 200 205 207 209 211 216 217 218 219 225 227
 228 229 230 231 232 236 237 240 241 246 248 252 253 254 256 258 259 261
 264 265 268 271 272 274 277 280 281 283 284 285 290 292 298 300 301 302
 303 305 308 312 313 317 321 322 323 326 327 329 331 333 336 337 340 342
 348 352 354 355 357 359 361 362 363 364 366 367 368 369 371 376 378 381
 382 384 385 386 390 391 392 393 395 396 398 400 401 402 404 