In [1]:
from utils import create_facts_and_examples
import numpy as np
import pandas as pd


In [2]:
N = 100

In [3]:
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)


In [4]:
#create artificial knowledge if A and B then Target

Target = A & B
df = pd.DataFrame({'A':A, 'B':B, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', ], output_dir='examples/a-b')


Target
[ 5  7 12 17 25 26 31 36 39 40 43 49 51 52 57 58 61 64 65 66 70 71 76 78
 80 81 82 87 88 93]
A
[ 1  4  5  6  7 10 12 14 17 25 26 27 30 31 34 35 36 38 39 40 43 47 48 49
 50 51 52 57 58 61 62 63 64 65 66 67 70 71 75 76 77 78 80 81 82 83 87 88
 92 93 94 95]
B
[ 0  2  5  7 12 16 17 18 19 21 22 23 24 25 26 28 31 32 33 36 39 40 41 42
 43 44 45 46 49 51 52 53 56 57 58 59 61 64 65 66 68 69 70 71 76 78 79 80
 81 82 84 86 87 88 89 93 97 98]


In [5]:
#create artificial knowledge if A and B and C then Target
Target = A & B & C
df = pd.DataFrame({'A':A, 'B':B, "C":C, "Target":Target})

create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C"], output_dir='examples/a-b-c')


Target
[ 5  7 12 17 25 26 40 49 57 64 70 78 80 82 87]
A
[ 1  4  5  6  7 10 12 14 17 25 26 27 30 31 34 35 36 38 39 40 43 47 48 49
 50 51 52 57 58 61 62 63 64 65 66 67 70 71 75 76 77 78 80 81 82 83 87 88
 92 93 94 95]
B
[ 0  2  5  7 12 16 17 18 19 21 22 23 24 25 26 28 31 32 33 36 39 40 41 42
 43 44 45 46 49 51 52 53 56 57 58 59 61 64 65 66 68 69 70 71 76 78 79 80
 81 82 84 86 87 88 89 93 97 98]
C
[ 3  4  5  7  8  9 10 12 17 18 23 25 26 30 32 40 41 44 45 46 47 48 49 57
 62 64 68 69 70 72 73 77 78 79 80 82 85 87 89 90 91 94 95 97 98]


In [6]:
N = 100
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)

Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d')


Target
[ 4  8 27 35 38 42 47 50 58 63 67 94]
A
[ 1  2  3  4  8 13 15 18 23 24 25 27 29 31 35 36 37 38 39 40 41 42 43 46
 47 48 50 51 53 54 55 58 59 60 61 63 64 67 69 70 72 74 75 77 78 80 81 83
 84 87 88 91 93 94 97 98 99]
B
[ 0  3  4  5  6  8 12 13 14 17 18 19 20 23 24 25 26 27 28 31 32 34 35 36
 37 38 42 43 44 45 46 47 48 50 52 53 58 59 60 61 62 63 64 65 67 68 73 76
 77 82 83 85 86 87 88 90 91 92 93 94 98 99]
C
[ 0  4  6  7  8 10 16 19 22 23 25 27 28 29 30 32 33 34 35 38 39 40 42 44
 45 47 48 50 53 54 55 56 57 58 62 63 65 66 67 68 69 70 72 74 76 79 80 81
 83 84 85 87 91 92 93 94]
D
[ 2  3  4  5  6  8  9 10 11 14 15 16 19 20 21 24 27 28 29 30 32 33 35 37
 38 41 42 43 47 50 55 57 58 60 61 63 64 65 67 68 69 71 72 74 78 82 84 85
 92 94 95 96 99]


In [7]:
N = 100
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)
A[0:20]=1
B[0:20]=1
C[0:20]=1
D[0:20]=1
Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d-first-20-true')


Target
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 49 77 81 88]
A
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 24 26 28
 30 35 37 39 40 41 42 43 46 48 49 50 52 53 55 59 60 63 64 71 75 76 77 78
 81 86 88 90 92 94 97 98]
B
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 22 23 24 26
 27 29 31 33 35 36 38 40 42 44 49 52 53 57 58 60 63 64 66 67 68 70 74 76
 77 79 81 82 83 88 92 93 94 95 96 98]
C
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 23 25 27 29
 31 34 35 37 39 41 46 47 49 54 56 57 58 65 67 68 71 72 74 77 78 79 80 81
 85 87 88 93 94 96 98 99]
D
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 22 25 28 29
 30 31 32 33 36 38 41 42 43 46 47 49 51 53 54 56 57 60 62 63 64 66 67 69
 70 73 76 77 78 81 83 86 88 90 97]


In [8]:
N = 1000
A =  np.random.randint(2, size=N)
B =  np.random.randint(2, size=N)
C =  np.random.randint(2, size=N)
D =  np.random.randint(2, size=N)

Target = A & B & C & D
df = pd.DataFrame({'A':A, 'B':B, "C":C, "D":D, "Target":Target})
create_facts_and_examples(df_=df, target='Target', 
                          predicates=['A', 'B', "C", "D"], output_dir='examples/a-b-c-d-1000')


Target
[  0  55  86 115 139 164 188 189 191 213 218 231 249 250 256 261 268 322
 326 341 366 372 379 382 415 416 420 434 435 447 452 459 463 477 518 523
 536 572 577 633 638 661 702 704 769 787 811 813 840 841 848 864 868 877
 885 893 902 931 940 941 951 953 983 984]
A
[  0   1   5   6   7   9  11  14  18  19  20  21  23  26  30  36  37  40
  41  42  43  46  47  48  50  52  53  54  55  57  59  60  61  64  67  68
  70  71  72  73  78  79  80  81  86  87  89  91  93  95  97  98  99 100
 101 102 106 108 109 110 111 113 115 116 117 118 122 123 126 129 130 132
 134 135 136 138 139 141 144 146 147 149 152 154 157 160 164 167 169 173
 174 175 176 178 182 183 184 186 188 189 191 197 200 205 207 211 213 214
 215 217 218 222 224 225 226 227 230 231 233 236 248 249 250 252 253 254
 255 256 258 261 262 264 265 268 271 273 277 285 288 289 290 291 293 295
 297 298 300 301 302 304 305 306 307 308 309 310 311 315 316 319 320 321
 322 325 326 327 328 329 330 332 333 334 336 338 340 341 342 343 345 346
